In [94]:
import numpy as np

In [95]:
a = np.array([1,2,3], dtype='int32')
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [96]:
print(a.ndim) # no. of dimensions
print(b.shape) 
print(a.dtype)

print(a.size) # size of array
print(a.itemsize) # size of each item in array
print(a.nbytes) # size of total array (size*itemsize)


1
(2, 3)
int32
3
4
12


In [97]:
# Accessing/Changing specific elements, rows, columns, etc
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r, c]
print(a[1, 5], a[1, -2])

# Get a specific row 
print(a[0, :])

# Get a specific column
print(a[:, 2])

# [startindex:endindex:stepsize]
print(a[0, 1:-1:2], a[0, 1:6:2])

a[1,5] = 20
a[:,2] = [1,2]
print(a)
a[:,2] = 5
print(a)

# 3-D
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Get specific element (work outside in)
print(b[0,1,1])
# replace 
b[:,1,:] = [[4,4],[7,7]]
print(b)
b[:,1,:] = [[9,9,9],[8,8]]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13 13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6] [2 4 6]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[[1 2]
  [4 4]]

 [[5 6]
  [7 7]]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [50]:
# Initializing Different Types of Arrays
# All 0s matrix
a = np.zeros((2,3))
print(a)
a = np.zeros((5))
print(a)

# All 1s matrix
print(np.ones((4,2,2), dtype='int32'))

# Any other number
print(np.full((2,2), 99, dtype='float32'))

# Any other number (full_like)
print(np.full_like(a, 4))
print(np.full(a.shape, 4))

# Random decimal numbers
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

# Random Integer values (includes left, excludes right)
print(np.random.randint(-4,8, size=(3,3)))

# The identity matrix
np.identity(3)

# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99. 99.]
 [99. 99.]]
[4. 4. 4. 4. 4.]
[4 4 4 4 4]
[[0.64347018 0.39974072]
 [0.06162483 0.5560409 ]
 [0.91939659 0.45369936]
 [0.39793443 0.70802229]]
[0.04176751 0.94891819 0.22768198 0.03982608 0.61622547]
[[ 5  0 -1]
 [ 7  2  6]
 [ 1  6  7]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [51]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
a = np.array([i for i in range(1,31)]).reshape(6,5)
print(a)
print(a[2:4, 0:2])
print(a[[0,1,2,3], [1,2,3,4]])
print(a[[0,4,5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]


In [54]:
# Be careful when copying arrays
a = np.array([1,2,3])
b = a # wrong (pointing to same thing)!
c = a.copy()
c[0] = 100
b[0] = 100
print(a, b, c)

[100   2   3] [100   2   3] [100   2   3]


In [60]:
# Mathematics (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

a = np.array([1,2,3,4])
print(a)
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)
# Take the sin
print(np.cos(a))
a += 2
a

b = np.array([1,0,1,0])
print(a + b)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[4 4 6 6]


In [62]:
# Linear algebra (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

# Find the determinant
c = np.identity(3)
np.linalg.det(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


1.0

In [65]:
# Statistics
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats, axis=0))

[[1 2 3]
 [4 5 6]]
1
[3 6]
[5 7 9]


In [73]:
# Reorganising arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((1,8))
print(after)
after = before.reshape((2,2,2))
print(after)

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [86]:
# Miscellaneous
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',').astype('int32')
print(filedata)

# Boolean Masking and Advanced Indexing
print((~((filedata > 50) & (filedata < 100)))) # any values not (greater than 50 and less than 100)
print(filedata[filedata > 50])
print(np.any(filedata > 50, axis = 0))
print(np.all(filedata > 50, axis = 1))

# indexing with a list
a = np.array([1,2,3,4,5,6,7])
a[[0,2,3,-1]]

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[[ True  True  True  True  True False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True False  True  True  True
   True  True  True  True False False]]
[196  75 766  75  55 999  78  76  88]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False]


array([1, 3, 4, 7])